open Core


type t =
  | Stop       (* halts execution *)
  | Add        (* addition operation *)
  | Mul        (* multiplication operation *)
  | Sub        (* subtraction operation *)
  | Div        (* integer division operation *)
  | Sdiv       (* signed integer division operation *)
  | Mod        (* modulo remainder operation *)
  | Smod       (* signed modulo remainder operation *)
  | Addmod     (* unsigned modular addition *)
  | Mulmod     (* unsigned modular multiplication *)
  | Exp        (* exponential operation *)
  | Signextend (* extend length of signed integer *)

  | Lt      (* less-than comparison *)
  | Gt      (* greater-than comparison *)
  | Slt     (* signed less-than comparison *)
  | Sgt     (* signed greater-than comparison *)
  | Eq      (* equality comparison *)
  | Iszero  (* simple not operator *)
  | And     (* bitwise AND operation *)
  | Or      (* bitwise OR operation *)
  | Xor     (* bitwise XOR operation *)
  | Not     (* bitwise NOT operation *)
  | Byte    (* retrieve single byte from word *)
  | Shl     (* bitwise SHL operation *)
  | Shr     (* bitwise SHR operation *)
  | Sar     (* bitwise SAR operation *)

  | Keccak256    (* compute KECCAK-256 hash *)

  | Address         (* get address of currently executing account *)
  | Balance         (* get balance of the given account *)
  | Origin          (* get execution origination address *)
  | Caller          (* get caller address *)
  | Callvalue       (* get deposited value by the instruction/transaction responsible for this execution *)
  | Calldataload    (* get input data of current environment *)
  | Calldatasize    (* get size of input data in current environment *)
  | Calldatacopy    (* copy input data in current environment to memory *)
  | Codesize        (* get size of code running in current environment *)
  | Codecopy        (* copy code running in current environment to memory *)
  | Gasprice        (* get price of gas in current environment *)
  | Extcodesize     (* get external code size (from another contract) *)
  | Extcodecopy     (* copy external code (from another contract) *)
  | Returndatasize  (* get size of return data buffer *)
  | Returndatacopy  (* copy return data in current environment to memory *)
  | Extcodehash     (* get external code hash (from another contract) *)

  | Blockhash     (* get hash of most recent complete block *)
  | Coinbase      (* get the block's coinbase address *)
  | Timestamp     (* get the block's timestamp *)
  | Number        (* get the block's number *)
  | Difficulty    (* get the block's difficulty *)
  | Gaslimit      (* get the block's gas limit *)

  | Pop          (* remove item from stack *)
  | Mload        (* load word from memory *)
  | Mstore       (* save word to memory *)
  | Mstore8      (* save byte to memory *)
  | Sload        (* load word from storage *)
  | Sstore       (* save word to storage *)
  | Jump         (* alter the program counter *)
  | Jumpi        (* conditionally alter the program counter *)
  | Pc           (* the program counter *)
  | Msize        (* get the size of active memory *)
  | Gas          (* get the amount of available gas *)
  | Jumpdest     (* set a potential jump destination *)

  | Push1 of Int.t        (* place 1 byte item on stack *)
  | Push2 of Int.t        (* place 2 byte item on stack *)
  | Push3 of Int.t        (* place 3 byte item on stack *)
  | Push4 of Int.t        (* place 4 byte item on stack *)
  | Push5 of Int.t        (* place 5 byte item on stack *)
  | Push6 of Int.t        (* place 6 byte item on stack *)
  | Push7 of Int.t        (* place 7 byte item on stack *)
  | Push8 of Int.t        (* place 8 byte item on stack *)
  | Push9 of Int.t        (* place 9 byte item on stack *)
  | Push10 of Int.t       (* place 10 byte item on stack *)
  | Push11 of Int.t       (* place 11 byte item on stack *)
  | Push12 of Int.t       (* place 12 byte item on stack *)
  | Push13 of Int.t       (* place 13 byte item on stack *)
  | Push14 of Int.t       (* place 14 byte item on stack *)
  | Push15 of Int.t       (* place 15 byte item on stack *)
  | Push16 of Int.t       (* place 16 byte item on stack *)
  | Push17 of Int.t       (* place 17 byte item on stack *)
  | Push18 of Int.t       (* place 18 byte item on stack *)
  | Push19 of Int.t       (* place 19 byte item on stack *)
  | Push20 of Int.t       (* place 20 byte item on stack *)
  | Push21 of Int.t       (* place 21 byte item on stack *)
  | Push22 of Int.t       (* place 22 byte item on stack *)
  | Push23 of Int.t       (* place 23 byte item on stack *)
  | Push24 of Int.t       (* place 24 byte item on stack *)
  | Push25 of Int.t       (* place 25 byte item on stack *)
  | Push26 of Int.t       (* place 26 byte item on stack *)
  | Push27 of Int.t       (* place 27 byte item on stack *)
  | Push28 of Int.t       (* place 28 byte item on stack *)
  | Push29 of Int.t       (* place 29 byte item on stack *)
  | Push30 of Int.t       (* place 30 byte item on stack *)
  | Push31 of Int.t       (* place 31 byte item on stack *)
  | Push32 of Int.t       (* place 32 byte item on stack *)

  | Dup1         (* copies the highest item in the stack to the top of the stack *)
  | Dup2         (* copies the second highest item in the stack to the top of the stack *)
  | Dup3         (* copies the third highest item in the stack to the top of the stack *)
  | Dup4         (* copies the 4th highest item in the stack to the top of the stack *)
  | Dup5         (* copies the 5th highest item in the stack to the top of the stack *)
  | Dup6         (* copies the 6th highest item in the stack to the top of the stack *)
  | Dup7         (* copies the 7th highest item in the stack to the top of the stack *)
  | Dup8         (* copies the 8th highest item in the stack to the top of the stack *)
  | Dup9         (* copies the 9th highest item in the stack to the top of the stack *)
  | Dup10        (* copies the 10th highest item in the stack to the top of the stack *)
  | Dup11        (* copies the 11th highest item in the stack to the top of the stack *)
  | Dup12        (* copies the 12th highest item in the stack to the top of the stack *)
  | Dup13        (* copies the 13th highest item in the stack to the top of the stack *)
  | Dup14        (* copies the 14th highest item in the stack to the top of the stack *)
  | Dup15        (* copies the 15th highest item in the stack to the top of the stack *)
  | Dup16        (* copies the 16th highest item in the stack to the top of the stack *)

  | Swap1         (* swaps the highest and second highest value on the stack *)
  | Swap2         (* swaps the highest and third highest value on the stack *)
  | Swap3         (* swaps the highest and 4th highest value on the stack *)
  | Swap4         (* swaps the highest and 5th highest value on the stack *)
  | Swap5         (* swaps the highest and 6th highest value on the stack *)
  | Swap6         (* swaps the highest and 7th highest value on the stack *)
  | Swap7         (* swaps the highest and 8th highest value on the stack *)
  | Swap8         (* swaps the highest and 9th highest value on the stack *)
  | Swap9         (* swaps the highest and 10th highest value on the stack *)
  | Swap10        (* swaps the highest and 11th highest value on the stack *)
  | Swap11        (* swaps the highest and 12th highest value on the stack *)
  | Swap12        (* swaps the highest and 13th highest value on the stack *)
  | Swap13        (* swaps the highest and 14th highest value on the stack *)
  | Swap14        (* swaps the highest and 15th highest value on the stack *)
  | Swap15        (* swaps the highest and 16th highest value on the stack *)
  | Swap16        (* swaps the highest and 17th highest value on the stack *)

  | Log0        (* Makes a log entry; no topics. *)
  | Log1        (* Makes a log entry; 1 topic. *)
  | Log2        (* Makes a log entry; 2 topics. *)
  | Log3        (* Makes a log entry; 3 topics. *)
  | Log4        (* Makes a log entry; 4 topics. *)

  | Jumpto             (* alter the program counter to a jumpdest -- not part of Instructions.cpp *)
  | Jumpif             (* conditionally alter the program counter -- not part of Instructions.cpp *)
  | Jumpv              (* alter the program counter to a jumpdest -- not part of Instructions.cpp *)
  | Jumpsub            (* alter the program counter to a beginsub -- not part of Instructions.cpp *)
  | Jumpsubv           (* alter the program counter to a beginsub -- not part of Instructions.cpp *)
  | Beginsub           (* set a potential jumpsub destination -- not part of Instructions.cpp *)
  | Begindata          (* begin the data section -- not part of Instructions.cpp *)
  | Returnsub          (* return to subroutine jumped from -- not part of Instructions.cpp *)
  | Putlocal           (* pop top of stack to local variable -- not part of Instructions.cpp *)
  | Getlocal           (* push local variable to top of stack -- not part of Instructions.cpp *)

  | Create        (* create a new account with associated code *)
  | Call          (* message-call into an account *)
  | Callcode      (* message-call with another account's code only *)
  | Return        (* halt execution returning output data *)
  | Delegatecall  (* like CALLCODE but keeps caller's value and sender *)
  | Create2       (* create new account with associated code at address `sha3(0xff + sender + salt + init code) % 2**160` *)
  | Staticcall    (* like CALL but disallow state modifications *)

  | Revert        (* halt execution, revert state and return output data *)
  | Invalid       (* invalid instruction for expressing runtime errors (e.g., division-by-zero) *)
  | Selfdestruct  (* halt execution and register account for later deletion *)

  | Unknown of String.t      (* unknown opcodes *)
  [@@deriving show { with_path = false }]

let to_string ?(split_instructions=false) t =
  let str = show t in
  match String.split ~on:' ' str with
  | [opcode] -> String.uppercase opcode
  | [opcode; value] ->
    let opcode = String.uppercase (String.drop_prefix opcode 1) in
    let value = String.strip ~drop:((=) '"') (String.drop_suffix value 1) in
    let sep = if split_instructions then "\n" else " " in
    opcode ^ sep ^ value
  | _ -> str
